apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prices-api-ingress
  namespace: prices-api
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "prices-api-ip"
    networking.gke.io/managed-certificates: "prices-api-cert"
    kubernetes.io/ingress.allow-http: "false"
    # HTTPS redirect
    ingress.gcp.kubernetes.io/pre-shared-cert: "prices-api-cert"
spec:
  rules:
  - host: api.company.com  #TODO
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prices-api-service
            port:
              number: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: prices-api-cert
  namespace: prices-api
spec:
  domains:
  - api.company.com #TODO
