apiVersion: v1
kind: Service
metadata:
  name: prices-api-service
  namespace: prices-api
  labels:
    app: prices-api
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: prices-api
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  sessionAffinity: None
